In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import linear_model
import statsmodels.api as sm
import tkinter as tk

In [2]:
df5 = pd.read_csv("fifth.csv", sep = ',', header=[0], encoding="utf-8") 
print(df5)

      Unnamed: 0  year  state  level  total_people_by_state_and_level  \
0              0     5      1      2                             3157   
1              1     5      1      1                           118401   
2              2     5      1      3                             5092   
3              3     5      1      7                           257632   
4              4     5      1      4                           140654   
5              5     5      1      5                           339865   
6              6     5      1      6                            57276   
7              7     5      1      9                            14992   
8              8     5      1      8                            64577   
9              9     5      2      2                             3007   
10            10     5      2      1                           294185   
11            11     5      2      3                            20085   
12            12     5      2      7               

In [3]:
df1 = pd.read_csv("Poblacion_Subordinada_Nivel_Ingresos.csv", sep = ',', header=[0], encoding="latin1") 
print(df1)

         Periodo Entidad_Federativa    Sexo     Grupo_edad  \
0       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
1       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
2       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
3       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
4       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
5       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
6       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
7       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
8       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
9       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
10      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
11      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
12      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
13      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
14      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
15      

In [4]:
df1.columns

Index(['Periodo', 'Entidad_Federativa', 'Sexo', 'Grupo_edad', 'Nivel_ingreso',
       'Numero_personas'],
      dtype='object')

In [5]:
from sklearn import preprocessing
label_encoded = preprocessing.LabelEncoder()

def encode_column(column):
    label_to_number = column
    label_to_number = label_encoded.fit_transform(label_to_number)
    return label_to_number

In [6]:
def add_column_to_df(columnName, df, valueColumn):
    df[columnName] = valueColumn
    return df1

In [7]:
age_to_number = encode_column(df1.Grupo_edad)
age_to_number

array([0, 0, 0, ..., 3, 3, 3])

In [8]:
df1 = add_column_to_df('Age_number', df1, age_to_number)
df1

Periodo Entidad_Federativa    Sexo     Grupo_edad  \
0       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
1       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
2       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
3       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
4       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
5       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
6       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
7       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
8       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
9       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
10      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
11      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
12      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
13      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
14      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
15      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
16      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
17      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
18      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
19      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
20      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
21      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
22      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
23      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
24      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
25      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
26      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
27      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
28      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
29      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
...          ...                ...     ...            ...   
225696  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225697  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225698  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225699  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225700  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225701  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225702  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225703  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225704  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225705  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225706  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225707  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225708  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225709  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225710  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225711  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225712  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225713  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225714  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225715  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225716  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225717  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225718  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225719  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225720  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225721  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225722  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225723  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225724  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225725  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   

                 Nivel_ingreso  Numero_personas  Age_number  
0              Menos de 1 s.m.             4284           0  
1             1 salario m¡nimo          

In [9]:
income_to_number = encode_column(df1.Nivel_ingreso)
income_to_number

array([1, 0, 4, ..., 1, 5, 3])

In [10]:
df1 = add_column_to_df('Income_number', df1, income_to_number)
df1



Periodo Entidad_Federativa    Sexo     Grupo_edad  \
0       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
1       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
2       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
3       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
4       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
5       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
6       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
7       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
8       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
9       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
10      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
11      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
12      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
13      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
14      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
15      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
16      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
17      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
18      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
19      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
20      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
21      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
22      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
23      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
24      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
25      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
26      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
27      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
28      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
29      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
...          ...                ...     ...            ...   
225696  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225697  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225698  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225699  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225700  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225701  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225702  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225703  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225704  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225705  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225706  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225707  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225708  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225709  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225710  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225711  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225712  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225713  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225714  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225715  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225716  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225717  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225718  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225719  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225720  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225721  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225722  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225723  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225724  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225725  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   

                 Nivel_ingreso  Numero_personas  Age_number  Income_number  
0              Menos de 1 s.m.             4284           0              1  
1         

In [11]:
state_to_number = encode_column(df1.Entidad_Federativa)
state_to_number

df1 = add_column_to_df('State_number', df1, state_to_number)
df1


Periodo Entidad_Federativa    Sexo     Grupo_edad  \
0       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
1       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
2       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
3       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
4       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
5       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
6       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
7       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
8       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
9       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
10      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
11      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
12      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
13      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
14      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
15      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
16      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
17      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
18      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
19      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
20      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
21      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
22      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
23      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
24      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
25      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
26      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
27      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
28      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
29      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
...          ...                ...     ...            ...   
225696  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225697  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225698  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225699  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225700  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225701  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225702  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225703  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225704  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225705  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225706  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225707  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225708  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225709  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225710  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225711  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225712  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225713  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225714  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225715  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225716  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225717  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225718  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225719  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225720  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225721  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225722  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225723  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225724  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225725  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   

                 Nivel_ingreso  Numero_personas  Age_number  Income_number  \
0              Menos de 1 s.m.             4284           0              1   
1       

In [12]:
sex_to_number = encode_column(df1.Sexo)
sex_to_number

df1 = add_column_to_df('Sex_number', df1, sex_to_number)
df1

Periodo Entidad_Federativa    Sexo     Grupo_edad  \
0       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
1       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
2       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
3       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
4       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
5       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
6       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
7       20050301     Aguascalientes  Hombre   15 A 24 A¥OS   
8       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
9       20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
10      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
11      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
12      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
13      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
14      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
15      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
16      20050301     Aguascalientes  Hombre   25 A 44 A¥OS   
17      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
18      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
19      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
20      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
21      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
22      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
23      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
24      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
25      20050301     Aguascalientes  Hombre   45 A 64 A¥OS   
26      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
27      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
28      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
29      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS   
...          ...                ...     ...            ...   
225696  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225697  20190601          Zacatecas  Hombre  65 A¥OS Y MAS   
225698  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225699  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225700  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225701  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225702  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225703  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225704  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225705  20190601          Zacatecas   Mujer   15 A 24 A¥OS   
225706  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225707  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225708  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225709  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225710  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225711  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225712  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225713  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225714  20190601          Zacatecas   Mujer   25 A 44 A¥OS   
225715  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225716  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225717  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225718  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225719  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225720  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225721  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225722  20190601          Zacatecas   Mujer   45 A 64 A¥OS   
225723  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225724  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   
225725  20190601          Zacatecas   Mujer  65 A¥OS Y MAS   

                 Nivel_ingreso  Numero_personas  Age_number  Income_number  \
0              Menos de 1 s.m.             4284           0              1   
1       

In [17]:
len_df1_cols = len(df1.columns)
print (list(df1.columns), len_df1_cols)

print (df1.columns)

['Periodo', 'Entidad_Federativa', 'Sexo', 'Grupo_edad', 'Nivel_ingreso', 'Numero_personas', 'Age_number', 'Income_number', 'State_number', 'Sex_number'] 10
Index(['Periodo', 'Entidad_Federativa', 'Sexo', 'Grupo_edad', 'Nivel_ingreso',
       'Numero_personas', 'Age_number', 'Income_number', 'State_number',
       'Sex_number'],
      dtype='object')


In [19]:
df1['Age_number'].unique()

array([0, 1, 2, 3, 4])

In [23]:
df1['Grupo_edad'].unique()

array(['15 A 24 A¥OS', '25 A 44 A¥OS', '45 A 64 A¥OS', '65 A¥OS Y MAS',
       'NO ESPECIFICADO'], dtype=object)

In [20]:
df1['Income_number'].unique()

array([1, 0, 4, 5, 6, 3, 8, 7, 2])

In [24]:
df1['Nivel_ingreso'].unique()

array(['Menos de 1 s.m.', '1 salario m¡nimo', 'M\xa0s de 2 hasta 3 s.m.',
       'M\xa0s de 3 hasta 5 s.m.', 'M\xa0s de 5 hasta 10 s.m.',
       'M\xa0s de 10 s.m.', 'No recibe ingresos', 'No especificado',
       'M\xa0s de 1 hasta 2 s.m.'], dtype=object)

In [21]:
df1['State_number'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 17])

In [25]:
df1['Entidad_Federativa'].unique()

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Chiapas', 'Chihuahua', 'Ciudad de M\x82xico',
       'Coahuila', 'Colima', 'Durango', 'Estado de M\x82xico',
       'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Michoac\xa0n',
       'Morelos', 'Nayarit', 'Nuevo Le¢n', 'Oaxaca', 'Puebla',
       'Queretaro', 'Quintana Roo', 'San Luis Potos¡', 'Sinaloa',
       'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz',
       'Yucat\xa0n', 'Zacatecas', 'Nacional'], dtype=object)

In [22]:
df1['Sex_number'].unique()

array([0, 1])

In [26]:
df1['Sexo'].unique()

array(['Hombre', 'Mujer'], dtype=object)

In [5]:
# print the dataframe
print (df)

# plot the Stock Index Price(dependent ) vs Interest Rate (independent)
plt.scatter(df['Interest_Rate'], df['Stock_Index_Price'], color='red')
plt.title('Stock Index Price Vs Interest Rate', fontsize=14)
plt.xlabel('Interest Rate', fontsize=14)
plt.ylabel('Stock Index Price', fontsize=14)
plt.grid(True)
plt.show()

# plot the Stock Index Price (dependent) vs Unemployment Rate (independent)
plt.scatter(df['Unemployment_Rate'], df['Stock_Index_Price'], color='green')
plt.title('Stock Index Price Vs Unemployment Rate', fontsize=14)
plt.xlabel('Unemployment Rate', fontsize=14)
plt.ylabel('Stock Index Price', fontsize=14)
plt.grid(True)
plt.show()


      Unnamed: 0  year  state  level  total_people_by_state_and_level  \
0              0     5      1      2                             3157   
1              1     5      1      1                           118401   
2              2     5      1      3                             5092   
3              3     5      1      7                           257632   
4              4     5      1      4                           140654   
5              5     5      1      5                           339865   
6              6     5      1      6                            57276   
7              7     5      1      9                            14992   
8              8     5      1      8                            64577   
9              9     5      2      2                             3007   
10            10     5      2      1                           294185   
11            11     5      2      3                            20085   
12            12     5      2      7               

KeyError: 'Interest_Rate'

In [15]:
# Split independent vars(X) and dependent var(Y)
# here we have 2 variables for multiple regression. 
#If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example.
#Alternatively, you may add additional variables within the brackets
X = df1[['Numero_personas','Age_number','State_number','Sex_number']] 
Y = df1['Income_number']
 
# with sklearn
regr = linear_model.LinearRegression()
regr.fit(X, Y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)


# prediction with sklearn
Num_persons = 50000
Age_number = 4
State_number = 20
Sex_number = 0
print ('Predicted Income group : \n', regr.predict([[Num_persons, Age_number, State_number, Sex_number]]))

Intercept: 
 4.482457479513848
Coefficients: 
 [-7.87335893e-06 -1.08152459e-01 -2.77350755e-03  6.77843532e-02]
Predicted Income group : 
 [3.60070954]


In [16]:
# with statsmodels
X = sm.add_constant(X) # adding a constant
 
model = sm.OLS(Y, X).fit()
predictions = model.predict(X) 
 
print_model = model.summary()
print(print_model)

/home/ealarap/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


                            OLS Regression Results                            
Dep. Variable:          Income_number   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.013
Method:                 Least Squares   F-statistic:                     719.0
Date:                Wed, 06 Nov 2019   Prob (F-statistic):               0.00
Time:                        09:28:59   Log-Likelihood:            -5.2099e+05
No. Observations:              225726   AIC:                         1.042e+06
Df Residuals:                  225721   BIC:                         1.042e+06
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               4.4825      0.016    2

In [27]:
 tkinter GUI
root= tk.Tk() 
 
canvas1 = tk.Canvas(root, width = 1200, height = 450)
canvas1.pack()

# with sklearn
Intercept_result = ('Intercept: ', regr.intercept_)
label_Intercept = tk.Label(root, text=Intercept_result, justify = 'center')
canvas1.create_window(260, 220, window=label_Intercept)

# with sklearn
Coefficients_result  = ('Coefficients: ', regr.coef_)
label_Coefficients = tk.Label(root, text=Coefficients_result, justify = 'center')
canvas1.create_window(260, 240, window=label_Coefficients)

# with statsmodels
print_model = model.summary()
label_model = tk.Label(root, text=print_model, justify = 'center', relief = 'solid', bg='LightSkyBlue1')
canvas1.create_window(800, 220, window=label_model)


# New_Interest_Rate label and input box
label1 = tk.Label(root, text='Type Interest Rate: ')
canvas1.create_window(100, 100, window=label1)

entry1 = tk.Entry (root) # create 1st entry box
canvas1.create_window(270, 100, window=entry1)

# New_Unemployment_Rate label and input box
label2 = tk.Label(root, text=' Type Unemployment Rate: ')
canvas1.create_window(120, 120, window=label2)

entry2 = tk.Entry (root) # create 2nd entry box
canvas1.create_window(270, 120, window=entry2)


def values(): 
    global New_Interest_Rate #our 1st input variable
    New_Interest_Rate = float(entry1.get()) 
    
    global New_Unemployment_Rate #our 2nd input variable
    New_Unemployment_Rate = float(entry2.get()) 
    
    Prediction_result  = ('Predicted Stock Index Price: ', regr.predict([[New_Interest_Rate ,New_Unemployment_Rate]]))
    label_Prediction = tk.Label(root, text= Prediction_result, bg='orange')
    canvas1.create_window(260, 280, window=label_Prediction)
    
button1 = tk.Button (root, text='Predict Stock Index Price',command=values, bg='orange') # button to call the 'values' command above 
canvas1.create_window(270, 150, window=button1)
 

root.mainloop()

SyntaxError: invalid syntax (<ipython-input-27-219c5b673a42>, line 1)